---
title: "csv to json conversion"
author: "Group77"
date: "10/14/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{python, results="hide"}
import csv, json

# Create Node Class for tree structure
class Node(object):
  def __init__(self, name, size=None, extra=None):
    self.name = name
    self.children = []
    self.size = size
    self.extra = extra

  # Def child relationship for json
  def child(self, cname, size=None, extra=None):
    child_found = [c for c in self.children if c.name == cname]
    if not child_found:
      _child = Node(cname, size, extra)
      self.children.append(_child)
    else:
      _child = child_found[0]
    return _child

  def as_dict(self):
    res = {'name': self.name}
    if self.size is None:
        res['children'] = [c.as_dict() for c in self.children]
    else:
        res['size'] = self.size

    if self.extra:
        res.update(self.extra)

    return res

# Define root node
root = Node('AirBNB_NewYork')

# read file and skip header
with open('data_test.csv', 'r') as f:
  reader = csv.reader(f)
  header = next(reader)

  # go through each line and create json object
  for row in reader:
    neighbourhood_group, neighbourhood, room_type, room_type_count = row
        
    root.child(neighbourhood_group).child(neighbourhood)\
                                   .child(room_type, size=room_type_count)

#Write json to ouput file
with open('data_test.json', 'w') as outfile:
    json.dump(root.as_dict(), outfile, indent=3)
```

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("

"))
```


